#build app
FROM node:14.15-alpine AS build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build



#stage pro
FROM nginx:1.12-alpine

COPY --from=build-stage /app/buil/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "deamon off;"]