version: '3.8'

services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    command: npm start
  server:
    build: .
    ports:
    - 8080:8080
    volumes:
      - .:/app
    environment:
      DB_URI: ""
    command: npm start
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - netFlims:/data/app 

volumes:
  netFlims:
  