version: '3.8'

services:
  client:
    build:
      context: ./client
      image: Dockerfile.prod
    ports:
      - 80:80
    restart: unless-stopped
  server:
    build: .
    ports:
    - 8080:8080
    environment:
      DB_URI: ""
    command: npm start
    restart: unless-stopped

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - netFlims:/data/app 
    restart: unless-stopped
    

volumes:
  netFlims:
  